name: Release Please

on:
  push:
    branches:
      - main

# permissions:
#   contents: write
#   pull-requests: write
#   repository-projects: read # needed for 'gh pr edit' https://github.com/cli/cli/issues/6274

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Release Please Action
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}