name: React on README.md Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  react-on-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Identify changed README.md files
        id: identify-changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'src/.*/README.md' > changed_readmes.txt
          cat changed_readmes.txt

      - name: Convert README.md files to HTML
        if: ${{ steps.identify-changes.outputs.changed_readmes != '' }}
        run: |
          while IFS= read -r readme; do
            output_dir=$(dirname "$readme")/docs
            mkdir -p "$output_dir"
            docker run --rm -v $(pwd):/workspace pandoc/core:3.5 --from=markdown --to=html --standalone=true --output="${output_dir}/README.html" "$readme"
          done < changed_readmes.txt

      - name: Commit and push changes
        if: ${{ steps.identify-changes.outputs.changed_readmes != '' }}
        run: |
          git config user.name "Chem O'Dun"
          git config user.email "chemodun@gmail.com"
          git add $(awk '{print $0 "/docs/README.html"}' changed_readmes.txt)
          git commit -m 'chore(docs): Update README.html files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}