name: React on MP4 Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/docs/videos/*.mp4'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  react-on-mp4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Identify changed MP4 files
        id: identify-changes
        run: |
          git show --name-status HEAD | grep 'src/.*/docs/videos/.*\.mp4' > changed_videos.txt
          cat changed_videos.txt
          echo "changed_videos=$(wc -l < changed_videos.txt)" >> $GITHUB_OUTPUT
          echo "new_or_updated_videos=$(grep -v '^D' changed_videos.txt | wc -l)" >> $GITHUB_OUTPUT

      - name: Install ffmpeg
        if: ${{ steps.identify-changes.outputs.new_or_updated_videos != '0' }}
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Process MP4 changes
        if: ${{ steps.identify-changes.outputs.changed_videos != '0' }}
        run: |
          chmod +x tools/convert_mp4_to_gif.sh
          tools/convert_mp4_to_gif.sh
        shell: bash

      - name: Commit and push changes
        if: ${{ steps.identify-changes.outputs.changed_videos != '0' }}
        run: |
          git config user.name "Chem O'Dun"
          git config user.email "chemodun@gmail.com"
          git add $(awk '{gsub(/videos/, "images", $2); gsub(/\.mp4$/, ".gif", $2); print $2}' changed_videos.txt)
          git commit -m 'docs(images): Update GIF files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}