name: React on README.md Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  react-on-readme:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Identify changed README.md files
        id: identify-changes
        run: |
          git show --name-status | grep 'src/.*/README.md' | awk '{print $2}' > changed_readmes.txt
          echo "changed_readmes=$(wc -l < changed_readmes.txt)" >> $GITHUB_OUTPUT

      -
        name: Install pandoc
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        uses: pandoc/actions/setup@v1
        with:
          version: 3.5

      -
        name: Convert README.md files to HTML
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        run: |
          while IFS= read -r readme; do
            output_file="${readme%.md}.html"
            echo "Converting $readme to $output_file"
            echo pandoc --from=markdown --to=html --standalone=true --output="$output_file" "$readme"
            pandoc --from=markdown --to=html --standalone=true --output="$output_file" "$readme"
          done < changed_readmes.txt

      -
        name: Commit and push changes
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        run: |
          git config user.name "Chem O'Dun"
          git config user.email "chemodun@gmail.com"
          git add $(awk '{gsub(/\.md$/, ".html"); print}' changed_readmes.txt)
          git commit -m 'chore(docs): Update README.html files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}