name: React on README.md Updates

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/README.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  react-on-readme:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4

      -
        name: Identify changed README.md files
        id: identify-changes
        run: |
          git show --name-status HEAD | grep 'src/.*/README.md' > changed_readmes.txt
          echo "changed_readmes=$(wc -l < changed_readmes.txt)" >> $GITHUB_OUTPUT

      -
        name: Install pandoc
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        uses: pandoc/actions/setup@v1
        with:
          version: 3.5

      -
        name: Process README.md changes
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        run: |
          while IFS=$'\t' read -r status readme; do
            output_file="${readme%.md}.html"
            if [[ "$status" == "A" || "$status" == "M" ]]; then
              echo "Converting $readme to $output_file"
              pandoc --from=markdown --to=html --standalone=true --output="$output_file" "$readme"
            elif [[ "$status" == "D" ]]; then
              echo "Deleting $output_file"
              git rm "$output_file"
            fi
          done < changed_readmes.txt

      -
        name: Commit and push changes
        if: ${{ steps.identify-changes.outputs.changed_readmes != '0' }}
        run: |
          git config user.name "Chem O'Dun"
          git config user.email "chemodun@gmail.com"
          git add $(awk '{gsub(/\.md$/, ".html", $2); print $2}' changed_readmes.txt)
          git commit -m 'docs(README): Update README.html files'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}